// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa-4AohuQIXz2afuBO6f0WtEI1HtdKixA',
    appId: '1:61201575676:android:51bf0b6df42b8182d9f179',
    messagingSenderId: '61201575676',
    projectId: 'jamguhtrivia',
    storageBucket: 'jamguhtrivia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMBuhPbafRsu9hy3HpYwZwscPgsRyn9hM',
    appId: '1:61201575676:ios:7d767f0ee22bdd4ad9f179',
    messagingSenderId: '61201575676',
    projectId: 'jamguhtrivia',
    storageBucket: 'jamguhtrivia.appspot.com',
    androidClientId: '61201575676-n623c37v9hmm4g8gvug4vambh6bb1p0e.apps.googleusercontent.com',
    iosClientId: '61201575676-god8lm4c5m5rtvrvvpa0mgrhftgf81l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.jamguhTriva',
  );
}
